// <auto-generated />
using System;
using BSBackupSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BSBackupSystem.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251130120657_CreateBasicModelForGames")]
    partial class CreateBasicModelForGames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BSBackupSystem.Model.App.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrencystamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalizedname");

                    b.HasKey("Id")
                        .HasName("pk_systemroles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("SystemRoles", (string)null);
                });

            modelBuilder.Entity("BSBackupSystem.Model.App.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("accessfailedcount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrencystamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("emailconfirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockoutenabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockoutend");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalizedemail");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalizedusername");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("securitystamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("twofactorenabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_systemusers");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("SystemUsers", (string)null);
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.HasKey("Id")
                        .HasName("pk_game");

                    b.ToTable("game", (string)null);
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.MoveSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("firstseen");

                    b.Property<string>("FullHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullhash");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("gameid");

                    b.Property<DateTimeOffset?>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastseen");

                    b.Property<string>("PreRetreatHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preretreathash");

                    b.Property<Guid?>("PreviousSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("previoussetid");

                    b.Property<int>("SeasonIndex")
                        .HasColumnType("integer")
                        .HasColumnName("seasonindex");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_moveset");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_moveset_gameid");

                    b.HasIndex("PreviousSetId")
                        .HasDatabaseName("ix_moveset_previoussetid");

                    b.ToTable("moveset", (string)null);
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.UnitOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("discriminator");

                    b.Property<Guid?>("MoveSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("movesetid");

                    b.Property<string>("Player")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("ResultReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resultreason");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<string>("UnitCoast")
                        .HasColumnType("text")
                        .HasColumnName("unitcoast");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unittype");

                    b.HasKey("Id")
                        .HasName("pk_unitorders");

                    b.HasIndex("MoveSetId")
                        .HasDatabaseName("ix_unitorders_movesetid");

                    b.ToTable("unitorders", (string)null);

                    b.HasDiscriminator().HasValue("UnitOrder");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claimtype");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claimvalue");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("roleid");

                    b.HasKey("Id")
                        .HasName("pk_systemroleclaims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_systemroleclaims_roleid");

                    b.ToTable("SystemRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claimtype");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claimvalue");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_systemuserclaims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_systemuserclaims_userid");

                    b.ToTable("SystemUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("loginprovider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("providerkey");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("providerdisplayname");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_systemuserlogins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_systemuserlogins_userid");

                    b.ToTable("SystemUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("roleid");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_systemuserroles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_systemuserroles_roleid");

                    b.ToTable("SystemUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("loginprovider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_systemusertokens");

                    b.ToTable("SystemUserTokens", (string)null);
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.BuildOrder", b =>
                {
                    b.HasBaseType("BSBackupSystem.Model.Diplo.UnitOrder");

                    b.ToTable("unitorders", (string)null);

                    b.HasDiscriminator().HasValue("BuildOrder");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.ConvoyOrder", b =>
                {
                    b.HasBaseType("BSBackupSystem.Model.Diplo.UnitOrder");

                    b.Property<string>("ConvoyFrom")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("from");

                    b.Property<string>("ConvoyTo")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("to");

                    b.ToTable("unitorders", (string)null);

                    b.HasDiscriminator().HasValue("ConvoyOrder");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.DisbandOrder", b =>
                {
                    b.HasBaseType("BSBackupSystem.Model.Diplo.UnitOrder");

                    b.ToTable("unitorders", (string)null);

                    b.HasDiscriminator().HasValue("DisbandOrder");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.HoldOrder", b =>
                {
                    b.HasBaseType("BSBackupSystem.Model.Diplo.UnitOrder");

                    b.ToTable("unitorders", (string)null);

                    b.HasDiscriminator().HasValue("HoldOrder");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.MoveOrder", b =>
                {
                    b.HasBaseType("BSBackupSystem.Model.Diplo.UnitOrder");

                    b.Property<string>("To")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("to");

                    b.ToTable("unitorders", (string)null);

                    b.HasDiscriminator().HasValue("MoveOrder");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.RetreatOrder", b =>
                {
                    b.HasBaseType("BSBackupSystem.Model.Diplo.UnitOrder");

                    b.Property<string>("To")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("to");

                    b.ToTable("unitorders", (string)null);

                    b.HasDiscriminator().HasValue("RetreatOrder");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.SupportHoldOrder", b =>
                {
                    b.HasBaseType("BSBackupSystem.Model.Diplo.UnitOrder");

                    b.Property<string>("Supporting")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("to");

                    b.ToTable("unitorders", (string)null);

                    b.HasDiscriminator().HasValue("SupportHoldOrder");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.SupportMoveOrder", b =>
                {
                    b.HasBaseType("BSBackupSystem.Model.Diplo.UnitOrder");

                    b.Property<string>("SupportingFrom")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("from");

                    b.Property<string>("SupportingTo")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("to");

                    b.ToTable("unitorders", (string)null);

                    b.HasDiscriminator().HasValue("SupportMoveOrder");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.MoveSet", b =>
                {
                    b.HasOne("BSBackupSystem.Model.Diplo.Game", null)
                        .WithMany("MoveSets")
                        .HasForeignKey("GameId")
                        .HasConstraintName("fk_moveset_game_gameid");

                    b.HasOne("BSBackupSystem.Model.Diplo.MoveSet", "PreviousSet")
                        .WithMany()
                        .HasForeignKey("PreviousSetId")
                        .HasConstraintName("fk_moveset_moveset_previoussetid");

                    b.Navigation("PreviousSet");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.UnitOrder", b =>
                {
                    b.HasOne("BSBackupSystem.Model.Diplo.MoveSet", null)
                        .WithMany("Orders")
                        .HasForeignKey("MoveSetId")
                        .HasConstraintName("fk_unitorders_moveset_movesetid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("BSBackupSystem.Model.App.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_systemroleclaims_systemroles_roleid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("BSBackupSystem.Model.App.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_systemuserclaims_systemusers_userid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("BSBackupSystem.Model.App.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_systemuserlogins_systemusers_userid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("BSBackupSystem.Model.App.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_systemuserroles_systemroles_roleid");

                    b.HasOne("BSBackupSystem.Model.App.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_systemuserroles_systemusers_userid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("BSBackupSystem.Model.App.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_systemusertokens_systemusers_userid");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.Game", b =>
                {
                    b.Navigation("MoveSets");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.MoveSet", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
