// <auto-generated />
using System;
using BSBackupSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BSBackupSystem.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260124052555_GamesHaveOwners")]
    partial class GamesHaveOwners
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BSBackupSystem.Model.App.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_system_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("index_role_normalized_name");

                    b.ToTable("system_roles", (string)null);
                });

            modelBuilder.Entity("BSBackupSystem.Model.App.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_system_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("idx_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("idx_users_normalized_user_name");

                    b.ToTable("system_users", (string)null);
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<string>("ForeignId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("foreign_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_games_owner_id");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.MoveSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<long>("FullHash")
                        .HasColumnType("bigint")
                        .HasColumnName("full_hash");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<DateTimeOffset?>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<long>("PreRetreatHash")
                        .HasColumnType("bigint")
                        .HasColumnName("pre_retreat_hash");

                    b.Property<Guid?>("PreviousSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_set_id");

                    b.Property<int>("SeasonIndex")
                        .HasColumnType("integer")
                        .HasColumnName("season_index");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("season_name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_move_sets");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_move_sets_game_id");

                    b.HasIndex("PreviousSetId")
                        .HasDatabaseName("ix_move_sets_previous_set_id");

                    b.ToTable("move_sets", (string)null);
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.UnitOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("discriminator");

                    b.Property<Guid?>("MoveSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("move_set_id");

                    b.Property<string>("Player")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("ResultReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_reason");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<string>("UnitCoast")
                        .HasColumnType("text")
                        .HasColumnName("unit_coast");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_type");

                    b.HasKey("Id")
                        .HasName("pk_unit_orders");

                    b.HasIndex("MoveSetId")
                        .HasDatabaseName("ix_unit_orders_move_set_id");

                    b.ToTable("unit_orders", (string)null);

                    b.HasDiscriminator().HasValue("UnitOrder");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_system_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_system_role_claims_role_id");

                    b.ToTable("system_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_system_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_system_user_claims_user_id");

                    b.ToTable("system_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_system_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_system_user_logins_user_id");

                    b.ToTable("system_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_system_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_system_user_roles_role_id");

                    b.ToTable("system_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_system_user_tokens");

                    b.ToTable("system_user_tokens", (string)null);
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.BuildOrder", b =>
                {
                    b.HasBaseType("BSBackupSystem.Model.Diplo.UnitOrder");

                    b.ToTable("unit_orders", (string)null);

                    b.HasDiscriminator().HasValue("BuildOrder");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.ConvoyOrder", b =>
                {
                    b.HasBaseType("BSBackupSystem.Model.Diplo.UnitOrder");

                    b.Property<string>("ConvoyFrom")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("from");

                    b.Property<string>("ConvoyTo")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("to");

                    b.ToTable("unit_orders", (string)null);

                    b.HasDiscriminator().HasValue("ConvoyOrder");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.DisbandOrder", b =>
                {
                    b.HasBaseType("BSBackupSystem.Model.Diplo.UnitOrder");

                    b.ToTable("unit_orders", (string)null);

                    b.HasDiscriminator().HasValue("DisbandOrder");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.HoldOrder", b =>
                {
                    b.HasBaseType("BSBackupSystem.Model.Diplo.UnitOrder");

                    b.ToTable("unit_orders", (string)null);

                    b.HasDiscriminator().HasValue("HoldOrder");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.MoveOrder", b =>
                {
                    b.HasBaseType("BSBackupSystem.Model.Diplo.UnitOrder");

                    b.Property<string>("To")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("to");

                    b.Property<string>("ToCoast")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("to_coast");

                    b.ToTable("unit_orders", (string)null);

                    b.HasDiscriminator().HasValue("MoveOrder");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.RetreatDisbandOrder", b =>
                {
                    b.HasBaseType("BSBackupSystem.Model.Diplo.UnitOrder");

                    b.ToTable("unit_orders", (string)null);

                    b.HasDiscriminator().HasValue("RetreatDisbandOrder");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.RetreatMoveOrder", b =>
                {
                    b.HasBaseType("BSBackupSystem.Model.Diplo.UnitOrder");

                    b.Property<string>("To")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("to");

                    b.Property<string>("ToCoast")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("to_coast");

                    b.ToTable("unit_orders", (string)null);

                    b.HasDiscriminator().HasValue("RetreatMoveOrder");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.SupportHoldOrder", b =>
                {
                    b.HasBaseType("BSBackupSystem.Model.Diplo.UnitOrder");

                    b.Property<string>("Supporting")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("to");

                    b.ToTable("unit_orders", (string)null);

                    b.HasDiscriminator().HasValue("SupportHoldOrder");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.SupportMoveOrder", b =>
                {
                    b.HasBaseType("BSBackupSystem.Model.Diplo.UnitOrder");

                    b.Property<string>("SupportingFrom")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("from");

                    b.Property<string>("SupportingTo")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("to");

                    b.ToTable("unit_orders", (string)null);

                    b.HasDiscriminator().HasValue("SupportMoveOrder");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.Game", b =>
                {
                    b.HasOne("BSBackupSystem.Model.App.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_games_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.MoveSet", b =>
                {
                    b.HasOne("BSBackupSystem.Model.Diplo.Game", null)
                        .WithMany("MoveSets")
                        .HasForeignKey("GameId")
                        .HasConstraintName("fk_move_sets_games_game_id");

                    b.HasOne("BSBackupSystem.Model.Diplo.MoveSet", "PreviousSet")
                        .WithMany()
                        .HasForeignKey("PreviousSetId")
                        .HasConstraintName("fk_move_sets_move_sets_previous_set_id");

                    b.Navigation("PreviousSet");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.UnitOrder", b =>
                {
                    b.HasOne("BSBackupSystem.Model.Diplo.MoveSet", null)
                        .WithMany("Orders")
                        .HasForeignKey("MoveSetId")
                        .HasConstraintName("fk_unit_orders_move_sets_move_set_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("BSBackupSystem.Model.App.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_system_role_claims_system_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("BSBackupSystem.Model.App.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_system_user_claims_system_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("BSBackupSystem.Model.App.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_system_user_logins_system_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("BSBackupSystem.Model.App.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_system_user_roles_system_roles_role_id");

                    b.HasOne("BSBackupSystem.Model.App.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_system_user_roles_system_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("BSBackupSystem.Model.App.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_system_user_tokens_system_users_user_id");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.Game", b =>
                {
                    b.Navigation("MoveSets");
                });

            modelBuilder.Entity("BSBackupSystem.Model.Diplo.MoveSet", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
